<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>VWOFmeSdk</RootNamespace>
    <AssemblyName>VWOFmeSdk</AssemblyName>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
    <PackageId>VWO.FME.Sdk</PackageId>
    <Version>1.55.1</Version>
    <Authors>VWO devs</Authors>
    <Company>Wingify</Company>
    <Product>VWO</Product>
    <Copyright>Wingify Software Pvt. Ltd.</Copyright>
    <Description>VWO Feature Management and Experimentation SDK for .Net</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591;1587;0105;0108;0168;0472;4014;1998;0414;SYSLIB0014</NoWarn>
    <IsPackable>true</IsPackable>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/wingify/vwo-fme-dotnet-sdk/</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://developers.vwo.com/v2/docs/fme-dotnet</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WingifyFmeSdk.NetStandard2.0\WingifyFmeSdk.NetStandard2.0.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\VWOFmeSdk\VWO.cs" Link="VWO.cs" />
    <Compile Include="..\VWOFmeSdk\VWOBuilder.cs" Link="VWOBuilder.cs" />
    <Compile Include="..\VWOFmeSdk\VWOClient.cs" Link="VWOClient.cs" />
    <Compile Include="..\VWOFmeSdk\Models\User\VWOInitOptions.cs" Link="Models\User\VWOInitOptions.cs" />
    <Compile Include="..\VWOFmeSdk\Models\User\VWOContext.cs" Link="Models\User\VWOContext.cs" />
    <Compile Include="..\VWOFmeSdk\Interfaces\Logger\LogTransport.cs" Link="Interfaces\Logger\LogTransport.cs" />
    <Compile Include="..\VWOFmeSdk\Packages\Logger\Enums\LogLevelEnum.cs" Link="Packages\Logger\Enums\LogLevelEnum.cs" />
    <Compile Include="..\VWOFmeSdk\Interfaces\Integration\IntegrationCallback.cs" Link="Interfaces\Integration\IntegrationCallback.cs" />
    <Compile Include="..\VWOFmeSdk\Packages\Storage\Connector.cs" Link="Packages\Storage\Connector.cs" />
    <Compile Include="..\VWOFmeSdk\Interfaces\Batching\IFlushInterface.cs" Link="Interfaces\Batching\IFlushInterface.cs" />
    <Compile Include="..\VWOFmeSdk\Models\BatchEventData.cs" Link="Models\BatchEventData.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Models\User\" />
  </ItemGroup>

</Project>
